"""Add tracking fields for GNN

Revision ID: 4555e6738a5c
Revises: f612ce2e441b
Create Date: 2026-06-25 19:31:09.443411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4555e6738a5c'
down_revision: Union[str, None] = 'f612ce2e441b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_ip_address', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_device_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_last_device_id'), 'users', ['last_device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_last_device_id'), table_name='users')
    op.drop_column('users', 'last_device_id')
    op.drop_column('users', 'last_ip_address')
    # ### end Alembic commands ###
