"""Add employee security fields

Revision ID: 4fd7bce4a1a8
Revises: 003_add_employee_audit_logs
Create Date: 2026-06-24 23:44:16.914138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd7bce4a1a8'
down_revision: Union[str, None] = '003_add_employee_audit_logs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_accounts', sa.Column('face_embedding', sa.String(), nullable=True))
    op.add_column('employee_accounts', sa.Column('trusted_device_id', sa.String(length=255), nullable=True))
    op.drop_constraint('employee_accounts_email_key', 'employee_accounts', type_='unique')
    op.drop_index('ix_employee_accounts_email', table_name='employee_accounts')
    op.create_index(op.f('ix_employee_accounts_email'), 'employee_accounts', ['email'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_mobile_number_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_mobile_number', table_name='users')
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.create_index('ix_users_mobile_number', 'users', ['mobile_number'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_mobile_number_key', 'users', ['mobile_number'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_employee_accounts_email'), table_name='employee_accounts')
    op.create_index('ix_employee_accounts_email', 'employee_accounts', ['email'], unique=False)
    op.create_unique_constraint('employee_accounts_email_key', 'employee_accounts', ['email'])
    op.drop_column('employee_accounts', 'trusted_device_id')
    op.drop_column('employee_accounts', 'face_embedding')
    # ### end Alembic commands ###
