"""Add missing foreign keys

Revision ID: 8c41182a2ac4
Revises: 4555e6738a5c
Create Date: 2026-06-30 00:55:42.712929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c41182a2ac4'
down_revision: Union[str, None] = '4555e6738a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'document_analyses', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'document_analyses', type_='foreignkey')
    # ### end Alembic commands ###
