"""Add Document and DocumentAnalysis models

Revision ID: f612ce2e441b
Revises: 4fd7bce4a1a8
Create Date: 2026-06-25 00:13:13.535489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f612ce2e441b'
down_revision: Union[str, None] = '4fd7bce4a1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('ocr_raw_text', sa.String(), nullable=True),
    sa.Column('layout_entities', sa.String(), nullable=True),
    sa.Column('vit_embedding', sa.String(), nullable=True),
    sa.Column('forgery_features', sa.String(), nullable=True),
    sa.Column('preliminary_fraud_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_analyses_document_id'), 'document_analyses', ['document_id'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'VERIFIED', 'NEEDS_REVIEW', 'REJECTED', name='documentuploadstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_document_analyses_document_id'), table_name='document_analyses')
    op.drop_table('document_analyses')
    # ### end Alembic commands ###
